export const products = [
  {
    id: "donut-1",
    name: "Donut",
    description: "Very tasty donut",
    sellingPrice: "9.99",
    mrp: "14.99",
    imageSrc: "https://i.ibb.co/LPK2qDr/donut.png",
  },
  {
    id: "pastry-2",
    name: "Pastry",
    description: "Very tasty pastry",
    sellingPrice: "19.99",
    mrp: "24.99",
    imageSrc: "https://i.ibb.co/dknK5SY/pastry.png",
  },
  {
    id: "cupcake-3",
    name: "Cupcake",
    description: "Very tasty cupcake",
    sellingPrice: "4.99",
    mrp: "9.99",
    imageSrc: "https://i.ibb.co/bbCj1L4/cupcake.png",
  },
  {
    id: "bread-4",
    name: "Bread",
    description: "Very tasty bread",
    sellingPrice: "16.49",
    mrp: "24.99",
    imageSrc: "https://i.ibb.co/mRMcgwN/bread.png",
  },
  {
    id: "donut-5",
    name: "Donut",
    description: "Very tasty donut",
    sellingPrice: "9.99",
    mrp: "14.99",
    imageSrc: "https://i.ibb.co/LPK2qDr/donut.png",
  },
  {
    id: "pastry-6",
    name: "Pastry",
    description: "Very tasty pastry",
    sellingPrice: "19.99",
    mrp: "24.99",
    imageSrc: "https://i.ibb.co/dknK5SY/pastry.png",
  },
  {
    id: "cupcake-7",
    name: "Cupcake",
    description: "Very tasty cupcake",
    sellingPrice: "4.99",
    mrp: "9.99",
    imageSrc: "https://i.ibb.co/bbCj1L4/cupcake.png",
  },
  {
    id: "bread-8",
    name: "Bread",
    description: "Very tasty bread",
    sellingPrice: "16.49",
    mrp: "24.99",
    imageSrc: "https://i.ibb.co/mRMcgwN/bread.png",
  },
  {
    id: "donut-9",
    name: "Donut",
    description: "Very tasty donut",
    sellingPrice: "9.99",
    mrp: "14.99",
    imageSrc: "https://i.ibb.co/LPK2qDr/donut.png",
  },
  {
    id: "pastry-10",
    name: "Pastry",
    description: "Very tasty pastry",
    sellingPrice: "19.99",
    mrp: "24.99",
    imageSrc: "https://i.ibb.co/dknK5SY/pastry.png",
  },
  {
    id: "cupcake-11",
    name: "Cupcake",
    description: "Very tasty cupcake",
    sellingPrice: "4.99",
    mrp: "9.99",
    imageSrc: "https://i.ibb.co/bbCj1L4/cupcake.png",
  },
  {
    id: "bread-12",
    name: "Bread",
    description: "Very tasty bread",
    sellingPrice: "16.49",
    mrp: "24.99",
    imageSrc: "https://i.ibb.co/mRMcgwN/bread.png",
  },
];
